language: generic
dist: bionic

install:
  - source .travis/texlive/texlive_install.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

before_script: cd $TRAVIS_BUILD_DIR/
script:
  # texliveonfly will try to download packages automatically
  - texliveonfly --compiler=xelatex --arguments="-shell-escape" --terminal_only hsrstud.dtx
  - texliveonfly --compiler=xelatex --arguments="-shell-escape" --terminal_only hsrzf-doc.tex
  # latexmk will automatically handle bibtex and references
  - latexmk -pdf -xelatex hsrstud.dtx
  - latexmk -pdf -xelatex hsrzf-doc.tex
