language: generic
dist: bionic

install:
  - source .travis/texlive/texlive_install.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

before_script: cd $TRAVIS_BUILD_DIR/
script:
  # texliveonfly will try to download packages automatically
  # latexmk will automatically handle bibtex and references
  - texliveonfly --compiler=xelatex --arguments="-shell-escape" --terminal_only hsrstud.dtx
  - latexmk -pdf -xelatex hsrstud.dtx
  - texliveonfly --compiler=xelatex --arguments="-shell-escape" --terminal_only hsrstud-classes.tex
  - latexmk -pdf -xelatex hsrstud-classes.tex
